name: IO testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v5
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
    - name: Create venv
      run: uv venv

    - name: Install deps
      run: uv pip install setuptools

    - name: Run tests
      run: uv run --dev pytest tests

